server:
  port: 8040
spring:
  application:
    name: Apli-Servi
  # Configuración de la base de datos PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/ani
    username: root
    password: 123456
    driver-class-name: org.postgresql.Driver
  # Configuraciones de JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  # Configuraciones de Servlet
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    path match:
      matching-strategy: ant-path-matcher
minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minio123minio
# JWT
security:
  jwt:
    #Spring1234
    key:
      private: 9414b0f9e189fc39821198d6f8f04a15c38a3efc71843d77673d4e1bbcc8cc72
    user:
      generator: AUTHBAT
    token:
      access-expiration: 3600000 # Duración de validez del token de acceso en milisegundos (1 hora)
      refresh-expiration: 2592000000 # Duración de validez del token de actualización en milisegundos (30 días)
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
# Configuración del logger (logback, log4j2, etc.)
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
  file:
    name: application.log
